#pragma config(Sensor, S4,     lightSensor,   sensorEV3_Color)
#pragma config(Motor,  motorB,          scannerMotor,  tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int light = getColorReflected(lightSensor);

	while(true) {

		datalogFlush();
		datalogClose();
		if (!datalogOpen(1020, 1, false)){
			displayCenteredTextLine(4,"Unable to open datalog");
		}

		light = getColorReflected(lightSensor);
		eraseDisplay();
		displayCenteredBigTextLine(5, "%d", light);

		datalogAddValue(1, light);
		sleep(1);

		datalogClose();
	}
}
